from typing import Any, Protocol


class ProjectionContract[T, D, R](Protocol):
    async def read(self, *args: Any, **kwargs: Any) -> T: ...

    async def transform(self, data: T) -> D: ...

    async def write(self, data: D) -> R: ...

    async def run(self, *args: Any, **kwargs: Any) -> R: ...
